export const products: IProduct[] = [
  {
    id: 1,
    name: "Nas – Illmatic",
    description:
      "El debut legendario de Nas, con rimas afiladas y beats crudos que definieron el rap de los 90. Un clásico absoluto.",
    price: 35,
    stock: 15,
    image: "https://ik.imagekit.io/oqtavryhy/NAS.webp?updatedAt=1751737392152",
    categoryId: 1,
  },
  {
    id: 2,
    name: "Kendrick Lamar – To Pimp a Butterfly",
    description: "Un viaje musical revolucionario que fusiona jazz, funk y rap, con letras profundas y políticas.",
    price: 40,
    stock: 10,
    image: "https://ik.imagekit.io/oqtavryhy/kendrick.webp?updatedAt=1751737324917",
    categoryId: 1,
  },
  {
    id: 3,
    name: "Bob Marley – Legend",
    description: "La antología definitiva del ícono del reggae. Paz, amor y resistencia en cada surco.",
    price: 45,
    stock: 12,
    image: "https://ik.imagekit.io/oqtavryhy/leyend.webp?updatedAt=1751737169068",
    categoryId: 3,
  },
  {
    id: 4,
    name: "The Notorious B.I.G. – Ready to Die",
    description: "Un retrato crudo y honesto de la vida en Brooklyn, con beats icónicos y flow legendario.",
    price: 38,
    stock: 8,
    image: "https://ik.imagekit.io/oqtavryhy/biggie.webp?updatedAt=1751737131881",
    categoryId: 1,
  },
  {
    id: 5,
    name: "Pink Floyd – The Dark Side of the Moon",
    description:
      "Un viaje psicodélico e introspectivo por los rincones de la mente. Rock progresivo en su máxima expresión.",
    price: 50,
    stock: 6,
    image: "https://ik.imagekit.io/oqtavryhy/pinkfloid.jpg?updatedAt=1751737863906",
    categoryId: 2,
  },
  {
    id: 6,
    name: "Tupac – All Eyez On Me",
    description:
      "Un álbum doble cargado de energía, mensajes sociales y estilo inconfundible. 2Pac en su mejor momento.",
    price: 42,
    stock: 9,
    image: "https://ik.imagekit.io/oqtavryhy/pac.webp?updatedAt=1751737099973",
    categoryId: 1,
  },
  {
    id: 7,
    name: "The Wailers – Catch a Fire",
    description: "El álbum que llevó el reggae al mundo. Bob Marley y su banda rompen fronteras.",
    price: 36,
    stock: 7,
    image: "https://ik.imagekit.io/oqtavryhy/Catchafire.webp?updatedAt=1751737206804",
    categoryId: 3,
  },
  {
    id: 8,
    name: "Led Zeppelin IV",
    description: "Rock puro y místico. Desde “Black Dog” hasta “Stairway to Heaven”, una obra inmortal.",
    price: 48,
    stock: 11,
    image: "https://ik.imagekit.io/oqtavryhy/zappelin.webp?updatedAt=1751737362689",
    categoryId: 2,
  },
  {
    id: 9,
    name: "Damian Marley – Welcome to Jamrock",
    description: "Un reggae moderno con letras punzantes y producción impecable. Hijo de leyenda, voz propia.",
    price: 39,
    stock: 13,
    image: "https://ik.imagekit.io/oqtavryhy/juniorgong.jpg?updatedAt=1751737292119",
    categoryId: 3,
  },
  {
    id: 10,
    name: "Outkast – Stankonia",
    description: "Creatividad desbordante y estilo único. Outkast redefiniendo el sonido del sur.",
    price: 37,
    stock: 10,
    image: "https://ik.imagekit.io/oqtavryhy/outkast.webp?updatedAt=1751737506938",
    categoryId: 1,
  },
  {
    id: 11,
    name: "The Rolling Stones – Let It Bleed",
    description: "Un clásico del rock con actitud cruda, blues, y energía rebelde.",
    price: 44,
    stock: 5,
    image: "https://ik.imagekit.io/oqtavryhy/stones.jpg?updatedAt=1751737897149",
    categoryId: 2,
  },
  {
    id: 12,
    name: "Peter Tosh – Legalize It",
    description: "Reggae combativo, lírica poderosa y sonido inmortal. Peter Tosh en estado puro.",
    price: 41,
    stock: 6,
    image: "https://ik.imagekit.io/oqtavryhy/petertosh.webp?updatedAt=1751737833002",
    categoryId: 3,
  },
  {
    id: 13,
    name: "Eminem – The Marshall Mathers LP",
    description: "Una descarga lírica brutal, emocional y polémica. Eminem en su máximo pico creativo.",
    price: 43,
    stock: 8,
    image: "https://ik.imagekit.io/oqtavryhy/eminem.jpg?updatedAt=1751737240164",
    categoryId: 1,
  },
  {
    id: 14,
    name: "Nirvana – Nevermind",
    description: "Rock sucio, emocional y revolucionario. Un símbolo de los 90 que rompió esquemas.",
    price: 47,
    stock: 14,
    image: "https://ik.imagekit.io/oqtavryhy/nirvana.webp?updatedAt=1751737456207",
    categoryId: 2,
  },
  {
    id: 15,
    name: "Steel Pulse – Handsworth Revolution",
    description: "Reggae consciente, rítmico y comprometido. Himnos que resisten al tiempo.",
    price: 40,
    stock: 10,
    image: "https://ik.imagekit.io/oqtavryhy/steel.jpg?updatedAt=1751737920512",
    categoryId: 3,
  },
];
